* How to learn these ideas

Learning hard concepts in Computer Science can take a lot of time. Along with reading the literature, grounding these ideas by working with them in an interactive editor would be of great aid to the learning process.

One of the steps that helped me was learning to program in a language with recursion. My previous exposure to this was languages where a procedural/iterative mode of organization was preferred like Javascript and Ruby, switching this to Scheme by learning [[https://github.com/prathyvsh/htdp][learning HtDP]] helped me a lot. Once I had a working knowledge of how computational structures can be built up and processed recursively, I got a base to ground the abstract ideas I learn and try them out using a development environment.

Once this was a strength, the next thing that was of immense help was to learn Lambda Calculus. It is a language with just three primitives (variables, abstraction, combination) that has deep implications for the mathematics side of programming languages. I have put together an (incomplete) guide to [[https://github.com/prathyvsh/lambda-calculus][learning it here]] and run a [[https://twitter.com/prathyvsh/status/1188787773441888257][twitter thread that captures the beautiful resources]] that I find along the way.

Once you have understood Lambda Calculus and is fluent in the notational language that is used to talk about it, you would have a good starting point to explore the literature further and with enough practice would be able to start understanding about the ideas being talked about and understand what import they have for daily programming practice. I am at this stage and it is leading me to different directions to explore logic, algebra, type theory, geometry, category theory, and relevant literature that you see linked here.

A common observation during these studies is that you’ll often become confused, stuck, or even at loss on how to even conceptualize a novel idea that you just come across. It is these points of inquiry that I think are very valuable in the learning process and what you do when you get stuck determines the learning outcome. A trajectory that I constantly recourse to when coming across a concept that I can’t understand is to refer to other resources on the same material that would give me a different perspective on what is being addressed. This gives multiple view/inspection points to the object of study and it really helps in connecting ideas together and gives you a richer conception for the import of the ideas being studied which in many cases gives me motivation to explore related material. And then if you go back to the stumbling point, it would make much more sense and you would be able to see it in a richer network of concepts that gives it meaning.

Hope that helps in giving a working base for people who are intrigued about these connections and feel free to touch base with me on [[https://twitter.com/prathyvsh][Twitter]] if you come across much difficulty when learning.
